server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fornecedor
    username: root  
    password: mysql@lucas
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: 'fornecedor'
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka